////////////////////////////////////////////////////////////////////////////////
Copyright (c) 2012, THE BOARD OF TRUSTEES OF THE LELAND STANFORD JUNIOR UNIVERSITY
All rights reserved.

Redistribution and use in source and binary forms, with or without modification,
are permitted provided that the following conditions are met:

   Redistributions of source code must retain the above copyright notice,
   this list of conditions and the following disclaimer.
   Redistributions in binary form must reproduce the above copyright notice,
   this list of conditions and the following disclaimer in the documentation
   and/or other materials provided with the distribution.
   Neither the name of the STANFORD UNIVERSITY nor the names of its contributors
   may be used to endorse or promote products derived from this software without
   specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED
OF THE POSSIBILITY OF SUCH DAMAGE.
////////////////////////////////////////////////////////////////////////////////

= Service Profile: r
:toc:

== Document Version
1.0

== Intent
The intent of this document is to provide an overview and meta data for the discovery of this service and its capabilities. This document may also be indexed and used to aid in service discovery. An access route can be utilized via the Service Registry home page.

== Name
r

== Purpose

=== Short
R as a service

=== Detailed
R as a service

== Service Model 
utility

== Tags
R, statistical, mathematical

== Owner
TBD

== Status
*IN PROGRESS*

== Deployment Overview

=== Service Handle
r

=== Protocol/Interface Classification
* synchronous
* STROMA compliant (Transport Protocol Agnostic)
* HTTP, RabbitMQ, ActiveMQ adapters included with default installation

=== Dependencies On Other Services And/Or Resources
N/A

.Dependencies
[options="header"]
|=========================================================
|Classification			|Name				|Notes
|=========================================================

=== Deployment Location
<The environments and clusters that this service is/will be deployed to go here>

== Service Capabilities

.Capabilities/Actions
[options="header"]
|=========================================================
|Action |Purpose                                                                                        |Tags                       |Status
|eval       | R as a service, STROMA compliant                                                          |R, STROMA, orchestration   |Complete
|evalstream | R as a service, NOT fully STROMA compliant, supports streaming of R script and response   |R, STROMA, orchestration   |Complete
|=========================================================

== Modifications To This Document

[options="header"]
|=========================================================
|Author             |Date       |Version    |Details
|Tom Angelopoulos   |8/27/13    |1.0        |Document Creation
|=========================================================
